### ISSUE TITLE
Version 1.2 not working on Windows

### ISSUE THREAD

**Issue by passarel** [HPInc/ml-git#59]
After installing version 1.2.0, the error message below is appearing, while trying any command. I tried installing using python setup.py install, from the main branch and from the tags 1.2.0 and 1.2.0_RC. Also tried installing via pip. When trying import the lib from inside Python (import ml_git), calling ml_git.__version__ returns 0.0.1 (not sure if this is related somehow)

Traceback (most recent call last):
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\Scripts\ml-git-script.py", line 33, in <module>
    sys.exit(load_entry_point('ml-git==1.2.0', 'console_scripts', 'ml-git')())
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\pkg_resources\__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\pkg_resources\__init__.py", line 2447, in load
    return self.resolve()
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\ml_git\main.py", line 7, in <module>
    from ml_git.commands import general
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\ml_git\commands\__init__.py", line 6, in <module>
    from . import general
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\ml_git\commands\general.py", line 17, in <module>
    @click.version_option(version=get_version(),  message='%(prog)s %(version)s')
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\ml_git\version.py", line 10, in get_version
    version_info = read_info_file(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'version.info')))
  File "C:\Users\borgesr\Anaconda3\envs\ml_git\lib\site-packages\ml_git\version.py", line 22, in read_info_file
    file = open(file_path, encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\borgesr\\Anaconda3\\envs\\ml_git\\lib\\site-packages\\version.info'

**Comment by andersonpablosilva** [comment]
Hi @passarel, thanks for reporting.

We identified the error and are already working on a hotfix. We will make the fix available as soon as possible.
